### ISSUE TITLE
Request to Remove Politically Charged Description from Example

### ISSUE THREAD

**Issue by hartmamt** [microsoft/TinyTroupe#16]
Hello, I noticed the following example in the code:

```python
"  - Might pretend to be a hard-core woke, but in reality that's just a facade to climb the corporate ladder  \n",
```

I wanted to point out that terms like woke have become heavily politicized, particularly by conservative discourse, often carrying loaded implications. Including this term in the example could unintentionally convey a political stance that may not be aligned with an inclusive or neutral tone in open-source software.

To help ensure that the project remains accessible and welcoming to all users, I suggest revising this line to remove references to woke and focus instead on an example that isn’t politically charged. Removing or rephrasing this language could enhance clarity and maintain a professional, neutral tone.

Thank you for considering this feedback!

**Comment by paulosalem** [comment]
That's a good point, thanks for catching it, I will address it in a next round of updates. I wrote many of the examples in a care-free way, partly for fun to be honest, but given the visibility and reach of open-source I feel you are absolutely right.

**Comment by hartmamt** [comment]
Appreciate that! This is great BTW, excited to use it!

**Comment by paulosalem** [comment]
I removed this part and a few others details. Thanks for sharing your concern!
