### ISSUE TITLE
Missing Dependency: `matplotlib.pyplot`

### ISSUE THREAD

**Issue by RektPunk** [microsoft/TinyTroupe#32]
I encountered an issue when using the package: it appears that `matplotlib.pyplot` is missing from the dependencies.
https://github.com/microsoft/TinyTroupe/blob/7ae16568ad1c4dea1381eda9dc8e0c3ff812d7a2/tinytroupe/profiling.py#L9

Thank you.

**Comment by RektPunk** [comment]
Thanks @Ankush1oo8, but it's in https://github.com/microsoft/TinyTroupe/pull/33 already. please close https://github.com/microsoft/TinyTroupe/pull/60

**Comment by Ankush1oo8** [comment]
Oh ok sorry!!!

**Comment by paulosalem** [comment]
Thanks folks, I merged this into _development_ branch. Soon will reach _main_.
